version: "3.9"
services:
  resume-db:
    image: mongo:6.0
    container_name: resume-db
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${local_username}
      MONGO_INITDB_ROOT_PASSWORD: ${local_password}
      MONGO_INITDB_DATABASE: ${mongo_database}
    volumes:
      - resume_data:/data/db

  ollama-service:
    container_name: ollama-service
    build:
      dockerfile: Dockerfile
    pull_policy: always
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_MODELS=/usr/share/ollama/.ollama/models
    healthcheck:
      test: "ollama --version && ollama ps || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ollama_data:/usr/share/ollama/.ollama/models

  resume-service:
    build:
      context: Resume-Builder-Service
      dockerfile: Dockerfile
    container_name: resume-service
    ports:
      - 8083:8083
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://${local_username}:${local_password}@resume-db:27017/${mongo_database}?authSource=admin
      SPRING_PROFILES_ACTIVE: cicd
    depends_on:
      - resume-db
      - ollama-service
volumes:
  resume_data:
  ollama_data:
