spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Resume-Builder-Service
  ai:
    ollama:
      chat:
        model: deepseek-r1:1.5b
      base-url: ${local_ollama_base_url} # Local Model
  data:
    mongodb:
      authentication-database: ${authentication_database}
      username: ${local_username}
      password: ${local_password}
      database: ${mongo_database}
      port: 27017
      host: localhost  # Assuming it's running locally

eureka:
  client:
    service-url:
      defaultZone: ${local_eureka_server}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8083
